name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t nspyc-pandoc .

      - name: Run Container and Generate PDF
        run: docker run -v ${{ github.workspace }}/output:/data/output nspyc-pandoc

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: $(grep 'subtitle:' convention.md | awk '{print $NF}')

      - name: Upload PDF as Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: convention.pdf
          path: output/convention.pdf
          if-no-files-found: error
